name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Show Service URL
      run: |
        echo "Access the app at: http://$(minikube ip):30080"